sudo: false
language: rust
rust:
  - stable
  - beta
  - nightly

install:
  - which cargo-coveralls || cargo install cargo-travis
  - which cargo-when || cargo install cargo-when
  - travis_wait cargo when --channel stable install rustfmt --force --vers 0.8.3
  - travis_wait cargo when --channel nightly install clippy --force || true
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - rustc -Vv
  - cargo -V
  - cargo check --verbose
  - cargo check --verbose --features "cli"
  - cargo check --verbose --features "cli serde serde_yaml serde_json"
  - cargo test  --verbose --features "cli serde serde_yaml serde_json"
  - ! which cargo-clippy || cargo when --channel nightly clippy -- --version
  - ! which cargo-clippy || cargo when --channel nightly clippy --features "cli serde serde_yaml serde_json"
  - cargo when --channel nightly bench --features "cli serde serde_yaml serde_json"
  - cargo when --channel stable doc --no-deps --all-features
  - cargo when --channel stable fmt -- --version
  - cargo when --channel stable fmt -- --write-mode=diff

after_success:
  - cargo when --channel stable coveralls

addons:
  apt:
    packages:
      # necessary for `cargo coveralls`
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

cache:
  apt: true
  cargo: true
before_cache:
    # Travis can't cache files that are not readable by "others"
    - chmod -R a+r $HOME/.cargo

notifications:
  email:
    on_success: never

env:
  global:
  - secure: FGosPYxgSM1Csyy2q/OiSW2KA7IDlIlLTODxwgszP/MIwOIMobAs5f+IqrEngEi3zKa0IPahQ3DZMZFAaNw9e1gI90ZQKpYgDQHNPeCtO0q4OV94RAjAFqhqVPxXwmNug88tm3NMokzzOafosWD8AzL7dYAx63KBpgCNZteW6CM=

