[package]

name = "liquid"
version = "0.9.1"
authors = ["Johann Hofmann <mail@johann-hofmann.com>"]
description = "The liquid templating language for Rust"
repository = "https://github.com/cobalt-org/liquid-rust"
documentation = "https://cobalt-org.github.io/liquid-rust/"
readme = "README.md"
categories = ["template-engine"]
keywords = ["liquid", "template", "templating", "language", "html"]
license = "MIT"

build = "build.rs"

[dependencies]
regex = "0.2"
lazy_static = "0.2"
chrono = "0.3"
unicode-segmentation = "1.1"
itertools = "0.6.0"

[build-dependencies]
skeptic = "0.9"

[dev-dependencies]
difference = "1.0"
skeptic = "0.9"

[features]
default = ["extra-filters"]

extra-filters = []

dev=[]
